### ISSUE TITLE
API to retrieve the write-ups is using POST instead of GET

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#27]
Semantically HTTP GET is used for fetching the records and POST is used for creating a record.
The app is currently using POST request for retrieving the write-ups. If this is done to enable sending filter parameters in the request body, the same could be achieved using url parameters in a GET request

**Comment by ericholsen** [comment]
I know, but I don't want student names revealed in an HTTP GET request.  I don't know how to hide them
