### ISSUE TITLE
Clicking on the Logo text takes to Login page

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#28]
After logging in I was able to see the writeups. But when I click on the application logo, it takes me to the login page. However the Logout link indicates that the user is still logged in.

![image](https://user-images.githubusercontent.com/15967687/114290531-29ca4c80-9a35-11eb-9988-32ef9da327bb.png)

**Comment by ericholsen** [comment]
clicking on the logo did not result in the logout.js function being run.  Another bug I had recently introduced and not found made it so the user wasn't really logged out. I fixed both

**Comment by eljog** [comment]
Cool.
But as a common behavior in the web applications, clicking on the logo should not trigger a logout. Users generally expect this link to take them to home page.

**Comment by ericholsen** [comment]
Actually, I subsequently made it so clicking the logo doesn't do anything anymore.  My app doesn't really have a Home Screen.  And I changed it so the log out button says login and is active when on the login screen.
