### ISSUE TITLE
Security: Able to hit the API urls without logging in 

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#29]
API urls are un authenticated. I can run the following command in a `bash shell` to retrieve writeups without logging in.

```
 curl -k 'https://j2qz7jwvh7.execute-api.us-east-1.amazonaws.com/testing/writeups'   -H 'authority: j2qz7jwvh7.execute-api.us-east-1.amazonaws.com'   --data-raw '{"start_date" : "2021-04-01","end_date" : "2021-04-21","type" : "all","student" : "all"}'
```

Beyond the security implications, a malicious user can write a script to send millions of write-up creation requests. That might result in a huge AWS bill to you.

**Comment by ericholsen** [comment]
user and code credentials are now sent in body of request and authenticated first
