### ISSUE TITLE
Github Project could be feature oriented

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#30]
The work is organized into three [github projects](https://github.com/ericholsen/swdv691-write-ups-web-app/projects), based on the functional/component aspect (UI/DB/Service). This is helpful if different teams are in charge of each of those functions.

When a product is developed by feature teams, or a single developer, it would be beneficial to organize the work in terms of features. For example, `User Login` story will do three tasks namely, Login page UI, login API, and necessary backend db table.

This is just suggestion on how project can be structured around features rather than components. **However it may not be ideal to make a change half way though the project**.

**Comment by ericholsen** [comment]
I appreciate the thoughts and will consider that way of looking things in future projects.  Or perhaps when I rebuild this one after everything I learn about what not to do.
