### ISSUE TITLE
Non admins can hack to delete write-ups

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#32]
Application is using a `sessionStorage` property to distringuish between an admin and non-admin user.
A non-admin user can easily tweak this property and then delete the records.
I was able to do that using the user named `nonadmin`

![image](https://user-images.githubusercontent.com/15967687/114291192-38673280-9a3a-11eb-8e08-2079ecef5d83.png)

This is where a server side authorization check is critical. Client side validations should not be trusted as a sole form of verification.

**Comment by ericholsen** [comment]
changed admin status to be server side, status no longer stored in session storage, user status is checked whenever the page is reloaded.
