### ISSUE TITLE
Delete API using POST method instead of DELETE

### ISSUE THREAD

**Issue by eljog** [ericholsen/swdv691-write-ups-web-app#33]
Semantically HTTP DELETE method is used for deleting records.
The app is currently using POST request for deleting the write-ups.

General form of an a delete API call would be:
`DELETE /api/write-ups/{record_id}`

**Comment by ericholsen** [comment]
i'm sending user credentials also to authenticate, so I want them hidden in the body of the post

**Comment by eljog** [comment]
FYI, an alternative and standard way to send credentials in HTTP is using Auth headers

**Comment by ericholsen** [comment]
I'm sure at some point I'll figure out how to do that.  After the class I plan to redo the app and use cognito.  I just haven't been able to figure out how to do that yet.
